### ISSUE TITLE
Websocket connection closed with EOF leads to a busy loop

### ISSUE THREAD

**Issue by sorfks** [philippseith/signalr#100]
In some cases (reproduced relatively often if refreshing a page from the Firefox browser), the websocket connection can be closed with EOF before a full frame is received on it.
This leads to a busy loop in function `readJSONFrames` from `jsonhubprotocol.go`.

I reproduced this with additional logging added as captured in this pull request: https://github.com/sorfks/signalr/pull/1/files
And a log snippet for such a run is attached [log-snippet.txt](https://github.com/philippseith/signalr/files/7498887/log-snippet.txt)

**Comment by sorfks** [comment]
Additional note: If I remove the `panic` after a number of busy loops, the issue also reproduces the leak of goroutines as mentioned in #91 by leading to a very fast OOM condition.

**Comment by philippseith** [comment]
The PR is contains a lot of logging in new way, currently not used in the package, so I don't like to have it in the master branch.
I tried to reproduce the behaviour with clicking frantically on refresh, but wasn't able to. 

But: I also removed the `!errors.Is(err, io.EOF)` from `readJSONFrames` and ran all tests with it. They all remained green. 
This means: The comment above the check for EOF doesn't apply to all the Connection implementations used in the test, and more important it doesn't apply to the serverSSEConnection and the websocketConnection. These two are the only ones which are important in practice.

So just removing the check will do it.

**Comment by philippseith** [comment]
> Additional note: If I remove the `panic` after a number of busy loops, the issue also reproduces the leak of goroutines as mentioned in #91 by leading to a very fast OOM condition.

The leak is fixed in #92 and #96 and does also not appear in the #99 which will be the new implementation for timeout handling.

**Comment by sorfks** [comment]
Sure, the PR is not meant to be merged, only to show the code changes I added to produce the log snippet.

And yes, this 

> I also removed the !errors.Is(err, io.EOF) from readJSONFrames and ran all tests with it

sounds right.

**Comment by philippseith** [comment]
See #101 

BTW: The endless loop would have ended after a timeout with #99 (but nevertheless there would have been thrashing)
