### ISSUE TITLE
Client: missing log messages with AutoReconnect option

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#105]
I'm using the client with logging like this:

	client, err := signalr.NewClient(context.Background(),
		signalr.WithAutoReconnect(c.connect(ts)),
		signalr.WithReceiver(c),
		signalr.Logger(easee.SignalrLogger(c.log.TRACE), true),
	)

If the `connect` method errors, hence a connection is never established, the log will not contain any messages.

I would have expected that, at least after the initial connect, the failed reconnect attempts would appear in the logs.

**Comment by philippseith** [comment]
See #106
