### ISSUE TITLE
Separate projects for client and server.

### ISSUE THREAD

**Issue by 3ldar** [philippseith/signalr#118]
Nice work, really appreciate it.
But would it be better to split this project into two? As no client code would need a server and the client in the same code base.

**Comment by philippseith** [comment]
Client and server are different use cases, that's true.
On the other hand, about 2000 of (currently) 3677 lines of code are shared between client and server. So we would end up with 3 packages, where changes in the base package (maybe to realise a feature for one of the derived packages) would influence both.
Furthermore, it more expressive to write `signalr.NewServer(...)` than `server.New(...)`. 
One can argue why not import it as `import signalr "github.com/philippseith/signalr/server` and write `signalr.New(...)` but then `New(...)` should be renamed to  `NewServer(...)` which leads to naming redundancy when the package is imported without the alias.

**Comment by 3ldar** [comment]
Well, then we need 3 packages: core, client, and server 😄 . And also I think naming it `NewServer(...)` is not redundant it is just explicit and it's better to be explicit when you initialize things. If your package had only one structure to initialize with `New(....)` it might be ok (still debatable :smiley: ) but other than that, being explicit would be my choice.
