### ISSUE TITLE
Noisy repeating debug messages in client

### ISSUE THREAD

**Issue by fabian-h** [philippseith/signalr#122]
I'm currently trying to use only the client part of this library, the server is a .NET 6 application. This works in general, but I am getting some weird debug messages that I couldn't figure out how to stop. I've created a minimal example that still shows this behaviour for me. The real code is listening for events from the server using a receiver, but the issue appears even if I remove that part. The server is also not sending any messages in this case, this always happens when I connect with the client.

```
func connectSignalR(address string) {
	ctx := context.Background()
	conn, _ := signalr.NewHTTPConnection(ctx, address)

	client, _ := signalr.NewClient(ctx, signalr.WithConnection(conn))

	client.Start()

	<-client.WaitForState(ctx, signalr.ClientConnected)
	fmt.Printf("Connected\n")

	<-client.WaitForState(ctx, signalr.ClientClosed)
	fmt.Printf("Connection closed\n")
}
```

The result looks like the following in the terminal

```
level=debug caller=options.go:119
level=debug caller=options.go:119
level=debug caller=options.go:119
level=debug caller=options.go:119
Connected
level=debug caller=options.go:119
```

The output continues if I leave the program running. I looked at the options.go line mentioned, but I could not figure out what exactly is happening here and why I get this output.

The only mentions of configuring the logging I found in the documentation was the testLogConf.json and I didn't touch that. This message also seems kinda useless, so it probably isn't an intentional one anyway. 

Any idea where this message is coming from and how to silence it?

**Comment by philippseith** [comment]
you can disable logging at all by passing `Logger(log.NewLogfmtLogger(ioutil.Discard), false)` to `NewClient` (`log` is `github.com/go-kit/kit/log`)

**Comment by philippseith** [comment]
@fabian-h Did this solve your problem?

**Comment by fabian-h** [comment]
Thank you, yes it did remove these repeating messages. Just in case anyone else needs this, the code I used is the following (I was confused for a moment which `Logger` was meant at first):

```
client, err := signalr.NewClient(ctx,
		signalr.WithConnection(conn),
		signalr.WithReceiver(receiver),
		signalr.Logger(log.NewLogfmtLogger(ioutil.Discard), false))
```

I'm still not sure what logging I should expect from this library, the messages I wanted to silence don't have any real content. So these do look more like some accidentally triggered code to me. 

Even if I don't silence the logging, there are quite a few kinds of errors that don't trigger any logging by default at all. For example if you call a function from the server that doesn't exist on the receiver, I get silently disconnected. That is a bit confusing when starting out and are not sure yet about the details of using the library.

**Comment by philippseith** [comment]
The empty log messages with always the same caller info were introduced with a PR from https://github.com/dreamsxin/go-signalr/commit/92f1a7e876507dcc353993127caf8f824ddd6ad3. I hope it is fixed with https://github.com/philippseith/signalr/commit/469c33bbd6d9227f55c3d0cb4b074370d3c4bfbc
