### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by WanWanHsieh** [philippseith/signalr#131]
Hello, I have encountered the following CORS problem, how can I deal with it? Thank you

![image](https://user-images.githubusercontent.com/19661909/175199903-efe382b3-66f8-42a9-a9c4-473319d88c3f.png)

**Comment by philippseith** [comment]
There are various ways to solve CORS problems, see https://stackoverflow.com/a/35588856. If you like to solve it in the signalr server, see https://stackoverflow.com/a/45807578 for background info. PR appreciated.

**Comment by eshanCV** [comment]
@philippseith Is this resolved ?
