### ISSUE TITLE
Pushing Stream sends improper StreamInvocation to SignalR server

### ISSUE THREAD

**Issue by blue-shoes** [philippseith/signalr#133]
This is a result of debugging with the SignalR team from [here](https://github.com/dotnet/aspnetcore/issues/43347). Per the developers, the PushStream method uses a StreamInvocation, which should only be used when the hub method is returning a stream (i.e. server-to-client). I believe the PushStream method should instead be calling the InvocationMessage method with the proper streamIds, but I have not yet had the time to investigate this fix.

**Comment by philippseith** [comment]
Seems I misinterpreted the spec here. I will look into that.

**Comment by philippseith** [comment]
@blue-shoes, I tried to fix the problem in https://github.com/philippseith/signalr/tree/bugfix/%23133_PushStreams_sends_StreamInvocation
Can you please check if this solves your problem?

**Comment by blue-shoes** [comment]
This looks to have fixed the issue and it now works consistently with the Microsoft team guidance. Thank you for your quick response!

**Comment by davidfowl** [comment]
Thanks for keeping this implementation going @philippseith !

**Comment by philippseith** [comment]
I see still an open issue: PushStreams should return the result of the server method.  Maybe some work for the weekend :-)
