### ISSUE TITLE
Send events from outside the Hub

### ISSUE THREAD

**Issue by neimanpinchas** [philippseith/signalr#140]
I am trying to create the pattern below

Obviously my intent is to have the hub forward all events recived from the b.Events channel

For testing I've created the ticker, but its panicking with 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x127d24a]

goroutine 8 [running]:
github.com/philippseith/signalr.(*Hub).Clients(0xc00006a050?)
        C:/Users/ps/go/pkg/mod/github.com/philippseith/signalr@v0.6.0/hub.go:32 +0x8a
```
Apparently context is nil.

hub.go:29
```golang
func (h *Hub) Clients() HubClients {
	h.cm.RLock()
	defer h.cm.RUnlock()
	return h.context.Clients()
}
```

What is the preferred way of brodcasting events not triggered by a hub method?

This is my code
```golang
b := BusHardware{}
go b.WireUp()
hub := MyHub{}
go Serve(&hub)
go Ticker(&hub)
for event := range b.Events {
	hub.Clients().All().Send(event.a, event.b)
}

func Ticker(hub *MyHub) {
	uptimeTicker := time.NewTicker(5 * time.Second)

	for {
		<-uptimeTicker.C

		hub.Clients().All().Send("Bow", "")
	}
}

func Serve(hub *MyHub) {
	address := "localhost:5000"

	// create an instance of your hub

	// build a signalr.Server using your hub
	// and any server options you may need
	server, _ := signalr.NewServer(context.TODO(),
		signalr.UseHub(hub),
		// signalr.HubFactory(func() signalr.HubInterface {
		// 	return hub
		// }),
		signalr.KeepAliveInterval(2*time.Second))
```

**Comment by philippseith** [comment]
the hub is not initialised until a client connects to the server, but the for loop or the ticker are calling hub.Clients() earlier. 
To prevent using an hub before Initialize(), override it and keep track of the state.
Alternatively, you might create an PR for making the Hub methods behave nicely while uninitialised

**Comment by neimanpinchas** [comment]
Sure, I will do a PR.

**Comment by neimanpinchas** [comment]
What do you want to be the nicely return

nil?
empty HubClients
Also should the initialized flag be public or private?

**Comment by neimanpinchas** [comment]
What do you want to be the nicely return

nil?
empty HubClients
Also should the initialized flag be public or private?

**Comment by philippseith** [comment]
- Empty HubClients
- The initialized flag is a specific solution when a single hub instance is used for all requests. But his is not the standard case. In general, hubs are transient and the HubFactory / SimpleHubFactory should be used. Please don't add it to the signalr package.

But back to 
>What is the preferred way of brodcasting events not triggered by a hub method?
```go
server.HubClients().All().Send("bow", "")
```
