### ISSUE TITLE
message failed to read: read limited at 32769 bytes and the client doesn't reconnect

### ISSUE THREAD

**Issue by x0y0z0tn** [philippseith/signalr#143]
Hi,
 sometimes I get this error

```
level=info ts=2022-11-07T13:22:52.054734Z class=Client connection=1Fdtl_ixQZvEL6Mbhw3mgQ
hub=main.receiver ts=2022-11-07T13:22:52.054735Z
error="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
message=<nil> reaction="close connection"
level=info ts=2022-11-07T13:22:52.05502Z
connect="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes
```

after that, the client doesn't reconnect.

I create the client in this way

```
        client, err := signalr.NewClient(
                context.Background(), nil,
                signalr.WithReceiver(rcv),
                signalr.WithConnector(func() (signalr.Connection, error) {
                        logger.Debug("signalr client connecting...")

                        creationCtx, _ := context.WithTimeout(context.Background(), 10*time.Second)
                        if err != nil {
                                logger.Error(err)
                        }

                        return conn, err
                }),
                signalr.Logger(kitlog.NewLogfmtLogger(os.Stderr), true))
        if err != nil {
                logger.Error(err.Error())
        }

  
        client.Start()

        go func() {
                select {
                case result := <-client.Invoke("SubscribeToOperations", invokeData):
                        logger.Debugf("invk operations [%#v]", result)
                }
        }()
```

When it happens I can see the log `signalr client connecting...` although the `client` doesn't reconnect or I don't receive more messages from the server.

Any suggestion?
Thanks in advance.

**Comment by philippseith** [comment]
You hit the default ReadLimit of the `nhooyr.io` `websocket.Conn`. You can change it by passing `signalr.MaximumReceiveMessageSize(yourReceiveSizeLimit)` to `NewClient`

**Comment by x0y0z0tn** [comment]
thanks for your answer! I'm going to try it.

When the client reconnects, do I need to recall the `client.Invoke` function?

thanks again :)

**Comment by philippseith** [comment]
> When the client reconnects, do I need to recall the `client.Invoke` function?

I think so.

**Comment by x0y0z0tn** [comment]
I added these lines 

```
const maxMessageSize = 1 << 17
...
  client, err := signalr.NewClient(
    context.Background(), nil,
    signalr.WithReceiver(rcv),
    signalr.WithConnector(func() (signalr.Connection, error) {
      creationCtx, _ := context.WithTimeout(context.Background(), 10*time.Second)
      conn, err := signalr.NewHTTPConnection(creationCtx, address)
      if err != nil {
        logger.Error(err.Error())
      }
      return conn, err
    }),
    signalr.MaximumReceiveMessageSize(maxMessageSize),
    signalr.Logger(kitlog.NewLogfmtLogger(os.Stderr), false))
```

although I continue receiving this error message

```
class=Client connection=Arc8M0flSxtgMxRhPDBeMQ hub=main.receiver ts=2022-11-11T16:33:49.443483347Z
 error="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes" message=<nil> reaction="close connection"
deploy_1  | level=info ts=2022-11-11T16:33:49.443577347Z connect="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
```

**Comment by philippseith** [comment]
Setting the websocket read limit was only done on the server side. See #147.
@x0y0z0tn can you check if this does the trick?

**Comment by x0y0z0tn** [comment]
sure, I going to try and I going to tell you. thanks

**Comment by x0y0z0tn** [comment]
my first test was reduce the max size to 1 << 14 (16384 from `1 << 15 ~ 32KB`), to get the case faster 

```
const maxMessageSize = 1 << 14
```

I am not completely sure if it works correctly because I get the message in a few minutes, but the failed message has the number 32769.
I expected to see a 16384 in that message

```
level=info ts=2022-11-12T20:22:07.476327Z class=Client connection=rk1FPVLgEs3vBWQvO3x1Sg
hub=main.receiver ts=2022-11-12T20:22:07.476329Z
error="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
message=<nil> reaction="close connection"
level=info ts=2022-11-12T20:22:07.476629Z
connect="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
```

To be sure, my go.mod changed, I am using the commit with the fix 

```diff
--- a/go.mod
+++ b/go.mod
@@ -11 +10,0 @@ require (
-       github.com/philippseith/signalr v0.6.0
@@ -35,0 +35 @@ require (
+       github.com/philippseith/signalr v0.6.1-0.20221112193050-c42dfee6a459 // indirect
```

Now, I going to try with

```
const maxMessageSize = 1 << 16
```

Probably it could take some time to happen.

**Comment by x0y0z0tn** [comment]
with 

```
const maxMessageSize = 1 << 16
```

I got the same failed-to-read message with 32769 bytes

```
level=info ts=2022-11-12T21:15:04.225026298Z class=Client connection=aO1dQ3FiLVRiSlbB38UCYA
hub=main.receiver ts=2022-11-12T21:15:04.225026585Z
error="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
message=<nil> reaction="close connection"
level=info ts=2022-11-12T21:15:04.225429987Z
connect="*signalr.webSocketConnection: failed to read: read limited at 32769 bytes"
```

**Comment by x0y0z0tn** [comment]
over the changes of #147 I added these lines 

```
@@ -136,10 +137,17 @@ func NewClient(ctx context.Context, options ...func(Party) error) (Client, error
        if c.conn == nil && c.connectionFactory == nil {
                return nil, ErrUnableToConnect
        }
+
+       fmt.Printf("conn <%#v>\n", c.conn)
+
        // Pass maximum receive message size to the websocket
        if wsConn, ok := c.conn.(*webSocketConnection); ok {
+               fmt.Printf("!! wsConn <%#v>\n", wsConn.conn)
                wsConn.conn.SetReadLimit(int64(c.maximumReceiveMessageSize()))
        }
+
+       fmt.Printf("conn <%#v>\n", c.conn)
+
        return c, nil
 }
```

to check the state of `c.conn`, and I got 

```
conn <<nil>>
conn <<nil>>
```

maybe `c.conn` is not available in `NewClient` to set the limit.

**Comment by x0y0z0tn** [comment]
if I set those lines in the `run` function

```
@@ -212,0 +216,5 @@ func (c *client) run() error {
+       // Pass maximum receive message size to the websocket
+       if wsConn, ok := c.conn.(*webSocketConnection); ok {
+               wsConn.conn.SetReadLimit(int64(c.maximumReceiveMessageSize()))
+       }
+
```

with `MaximumReceiveMessageSize(1024)`, I can see a change in the log `failed to read: read limited at 1025 bytes`

```
level=info ts=2022-11-14T17:19:36.077806Z class=Client connection=KQemRkn9MWNis33F83NQDw
hub=signalr.receiver ts=2022-11-14T17:19:36.077809Z
error="*signalr.webSocketConnection: failed to read: read limited at 1025 bytes"
message=<nil> reaction="close connection"
level=info ts=2022-11-14T17:19:36.078098Z
connect="*signalr.webSocketConnection: failed to read: read limited at 1025 bytes"
```

although I am not sure if it could create other problem

**Comment by philippseith** [comment]
> over the changes of #147 I added these lines
> 
> ```
> @@ -136,10 +137,17 @@ func NewClient(ctx context.Context, options ...func(Party) error) (Client, error
>         if c.conn == nil && c.connectionFactory == nil {
>                 return nil, ErrUnableToConnect
>         }
> +
> +       fmt.Printf("conn <%#v>\n", c.conn)
> +
>         // Pass maximum receive message size to the websocket
>         if wsConn, ok := c.conn.(*webSocketConnection); ok {
> +               fmt.Printf("!! wsConn <%#v>\n", wsConn.conn)
>                 wsConn.conn.SetReadLimit(int64(c.maximumReceiveMessageSize()))
>         }
> +
> +       fmt.Printf("conn <%#v>\n", c.conn)
> +
>         return c, nil
>  }
> ```
> 
> to check the state of `c.conn`, and I got
> 
> ```
> conn <<nil>>
> conn <<nil>>
> ```
> 
> maybe `c.conn` is not available in `NewClient` to set the limit.

I oversaw you were using `WithConnector`. #147 fixed it only for `WithConnection`. I will move the adjustment to the right place. 
@x0y0z0tn please check the new fix

**Comment by x0y0z0tn** [comment]
Thanks, for the new commit!!

yes, if I moved my repo to your latest commit, with `max message size 1<<10`, I can see this message 

```
level=info ts=2022-11-19T17:03:08.686137Z
connect="*signalr.webSocketConnection: failed to read: read limited at 1025 bytes"
```

Your latest commit changes the max message size.
