### ISSUE TITLE
Is there a way to get values from the query string?

### ISSUE THREAD

**Issue by noenik** [philippseith/signalr#149]
If the connection is made with a query string, is it possible to get those values?

The intended use is auth: https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0

I've tried getting them from the context with something like this, but that does not seem to work:
```Go
func (hub *MyHub) OnConnected(connectionId string) {
        // ...
	token := hub.Context().Value("token")
        // ...
}
````

**Comment by philippseith** [comment]
IMHO, authentication should be handled on the `http.Handler` level. There are a lot of examples how to do that out there and many frameworks with support for various authentication providers.

**Comment by noenik** [comment]
> IMHO, authentication should be handled on the `http.Handler` level. There are a lot of examples how to do that out there and many frameworks with support for various authentication providers.

Thanks for the reply. I've opted for using chi so that I can handle it in middleware. I was originally reluctant to do that since we use gin for everything else. But it will do for now.
