### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by eshanCV** [philippseith/signalr#150]
Hi @philippseith,

I'm trying to run my client app on a different port and I have set the origin patterns using AllowOriginPatterns method on the server side with the * and http://localhost:3000/ values (almost every possible way with the URL).

But when I reload the client app "http://localhost:8080/chat/negotiate?negotiateVersion=1" API call gets failed with the CORS error.

Can you please let me know whether I missed anything? Do I need to use "InsecureSkipVerify"?

**Comment by philippseith** [comment]
If you are fine with SSE, you can handle the whole CORS thing in the `http.Handler` you pass to `http.ListenAndServe`.
Here is a modification for the `LogRequests` function from the chatsample, when the webpage is on localhost:8087 and the signalr server still on localhost:8086.

```go
func LogRequests(h http.Handler) http.Handler {
	// type our middleware as an http.HandlerFunc so that it is seen as an http.Handler
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                // sample CORS handling
		w.Header().Set("Access-Control-Allow-Origin", "http://localhost:8087")
		w.Header().Set("Access-Control-Allow-Credentials", "true")
		w.Header().Set("Access-Control-Allow-Headers", "X-Requested-With,X-SignalR-User-Agent")
		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		// wrap the original response writer, so we can capture response details
		wrappedWriter := wrapResponseWriter(w)
		start := time.Now() // request start time

		// serve the inner request
		h.ServeHTTP(wrappedWriter, r)

		// extract request/response details
		status := wrappedWriter.status
		uri := r.URL.String()
		method := r.Method
		duration := time.Since(start)

		// write to console
		fmt.Printf("%03d %s %s %v\n", status, method, uri, duration)
	})
}
``` 
I am not a CORS expert and the handling may get arbitrarily complicated, but in the essence that's it.

To support your cross origins with the "WebSockets" transport, you additionally need to add your cross origin urls with the https://github.com/philippseith/signalr/blob/7237db33c21b454ced6c212f290cde3f5aaf87d7/serveroptions.go#L64 or https://github.com/philippseith/signalr/blob/7237db33c21b454ced6c212f290cde3f5aaf87d7/serveroptions.go#L73 server options
