### ISSUE TITLE
Fallback on network blocking

### ISSUE THREAD

**Issue by thiagosoeiro** [philippseith/signalr#174]
Curious.. Will this library automatically and seamlessly fall back to Long Polling and/or Server-Sent Events when WebSockets are not supported by the server or blocked by a firewall/proxy? It's not clear from the docs https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-7.0#transports, so I just wanted to make sure. TY!

**Comment by philippseith** [comment]
The client negotiates with the server if to use SSE or WebSockets, Long Polling is not supported. 
Blocked WebSockets have to be handled with the WithConnector option. The contextFactory has to create the HttpConnection first with WebSockets as allowed protocol, and if this fails, create and return a new HttpConnection with SSE.
Eventually a stock contextFactory which does this could be included in the package. PR welcome.

**Comment by philippseith** [comment]
The client negotiates SSE/WebSockets with the server, but is not able to handle blocked WebSockets.

**Comment by philippseith** [comment]
@tsoeiroecore See #175 for fallback when WebSockets are blocked
