### ISSUE TITLE
Support for "old" servers

### ISSUE THREAD

**Issue by sruehl** [philippseith/signalr#194]
I have a server which responds with the old format (https://github.com/SignalR/SignalR) for negotation which looks like what can be found here: https://github.com/alexjorgef/signalr/blob/main/client.go#L14

I wonder what is necessary to make this lib (https://github.com/philippseith/signalr) support older servers too.
This is the root case for https://github.com/philippseith/signalr/issues/193

**Comment by philippseith** [comment]
- I could not find any written spec for the ASP.NET SignalR 1.x negotiation process.
- From the source you linked, one can see that the negotiate response looks similar, but has some unclear properties. What are the values of `protocolVersion`? How decide to use WebSockets seems clear, but how to differentiate between SSE and LongPolling?
- If you look at https://github.com/alexjorgef/signalr/blob/main/client.go#L174 even the messages seem to be serialized in a different way.

I don't guess this will work.
