### ISSUE TITLE
Go server and js client can't use websocket transport

### ISSUE THREAD

**Issue by MiyamuraMiyako** [philippseith/signalr#201]
I can't understand why `error 403`.

Server:
```golang
singnalrSvr, _ := signalr.NewServer(context.TODO(),
		signalr.SimpleHubFactory(&hub),
		signalr.KeepAliveInterval(15*time.Second),
		nil)

serverMux := http.NewServeMux()

singnalrSvr.MapHTTP(signalr.WithHTTPServeMux(serverMux), "/s")
go http.ListenAndServe("127.0.0.1:5005", serverMux)
```

Client:
```javascript
var connection = new signalR.HubConnectionBuilder()
        .withUrl("http://127.0.0.1:5005/s")
        .build();

connection
        .start({ pingInterval: 150000 })
        .then(async function () {
          console.log("Connected!");
        })
        .catch(function (err) {
          return console.error(err.toString());
        });
```

![图片](https://github.com/user-attachments/assets/2594facc-b7c7-4f79-a460-b61045cacf8c)

**Comment by philippseith** [comment]
Looks like a CrossOrigin access. The origin of the client requests also needs to be http://127.0.0.1:5005. This is generally achieved by serving the client webpage with the same  http server as the signalr API. 
See the chatsample, especially this line:  https://github.com/philippseith/signalr/blob/7138ab5c621e342fe7862c570c00112633aa7079/chatsample/main.go#L140
