### ISSUE TITLE
Go client side with websocket support

### ISSUE THREAD

**Issue by soxft** [philippseith/signalr#204]
I am trying to use philippseith/signalr to build the client side in Golang, but I can only find the NewHTTPConnection method. How can I establish a WSS connection?

**Comment by philippseith** [comment]
A websocket connection is always started by a http negotiation. See https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md. You can specify the transport for the client by using the WithTransports option when calling NewHTTPConnection
