### ISSUE TITLE
Cannot send to Caller on go client

### ISSUE THREAD

**Issue by kzeedev** [philippseith/signalr#208]
using signalr client in go application cannot respond to Caller.

```
type receiver struct {
	signalr.Hub
}

func (c *receiver) Receive(msg string) {
	fmt.Println(msg)
	c.Clients().Caller().Send("SendMessage", "Client2", "Got your message")
}

func makeClient(address string) (signalr.Client, error) {
	ctx := context.Background()
	rcv := &receiver{}
	// Create a Connection
	creationCtx, _ := context.WithCancel(ctx)
	// Create the client and set a receiver for callbacks from the server
	client, err := signalr.NewClient(ctx,
		signalr.WithHttpConnection(creationCtx, address),
		signalr.WithReceiver(rcv))
	if err != nil {
		return nil, err
	}
	// Start the client loop
	client.Start()
	return client, nil
}
```

But in Receive func when running `c.Clients().Caller().Send` getting this error:
`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by philippseith** [comment]
A receiver is just an object which will receive server side calls to client methods (e.g. callbacks). A contained Hub member is not automagically instantiated. 
You can send back to the server from the receiver either if the callback has a return value or by passing the client instance to the receiver and using [Client.Send](https://github.com/philippseith/signalr/blob/c0d0ccd51b690976e3032b6a7da30c76928132c6/client.go#L111)
