### ISSUE TITLE
binding to mux other than http.ServeMux is difficult

### ISSUE THREAD

**Issue by davidalpert** [philippseith/signalr#30]
while trying to use this package with [gorilla/mux](https://github.com/gorilla/mux) I couldn't figure out how to bind the server to my router.

I came up with two ideas on how to use this package with `gorilla/mux` (and potentially other community mux implementations) more easily:

1. #28 expose `HttpMux` as an `http.Handler` implementation
1. #29 introduce a new `signalr.MappableRouter` interface and bind `server.MapHTTP` through this interface

**Comment by philippseith** [comment]
I am favouring #29, because #28 requires the user to map /negotiate manually. Negotiation is not a topic the user should be bothered with.

**Comment by davidalpert** [comment]
I think it's good to have the option though.

Easy to configure by default but also possible to configure manually if you need/want to?

**Comment by philippseith** [comment]
If you do not map Negotiate, no connection could be established. It feels not good to give the option to do it wrong.

**Comment by davidalpert** [comment]
I have some emotional baggage from stubbing my toes against classes in the .NET Framework which are marked `internal` 🤣 

I understand your hesitation to expose that option to do it wrong.

#29 at least decreases that coupling to `http.ServerMux` to a minimum. 👍

**Comment by davidalpert** [comment]
closed #28

**Comment by davidalpert** [comment]
#29 has been merged 🎉
