### ISSUE TITLE
[Demo]Websocket connection fails

### ISSUE THREAD

**Issue by cristianserban93** [philippseith/signalr#46]
Hello,

First of all, great tool !!

I am having some difficulties running the demo. I am having a problem with WebSocket failing to connect.

Any tips?

Thanks!

![issue](https://user-images.githubusercontent.com/19717996/121917928-40936500-cd3e-11eb-9721-98a08acc50b3.JPG)

**Comment by philippseith** [comment]
This happened because the sample contains a middleware for logging http status codes which did not implement http.Hijacker.
It is fixed with https://github.com/philippseith/signalr/commit/1f63bef6088aa9c1e45010293cd2486cdee6b9b3
cc @davidalpert
