### ISSUE TITLE
Missing client example

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#61]
The README mentions js clients but does not give an example for the Go client. It would be great to have end-to-end Go examples available.

**Comment by philippseith** [comment]
There is a client in https://github.com/philippseith/signalr/blob/8403ef3ea309393b8117715a5eef7bfd58ec64dc/chatsample/main.go#L139 
and a lot of clients in the tests. 

But you are right, a working sample would be nice.

**Comment by philippseith** [comment]
See https://github.com/philippseith/signalr/commit/35f4328f4756573978c70b296400bd99410cd231 and
https://github.com/philippseith/signalr/commit/ecfde8368ec73d6a6a0571c5d810c08ede99e53b
