### ISSUE TITLE
Add client reconnection

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#66]
I'd like using signalr in a long-running server application (https://github.com/evcc-io/evcc/pull/1586). That requires reconnecting if necessary. At this time I couldn't find out how to enable this as part of this module or detect connection drop from consumer side?

**Comment by andig** [comment]
I couldn't immediately see how to do this but imho there are two aspects:

- [x] allow consumers to detect that the loop has closed https://github.com/philippseith/signalr/pull/68
- [ ] add a `reconnect` option to the client

Might also make option naming consistent between client and http connection (`With...`?)

**Comment by philippseith** [comment]
I think both ways for reconnecting should be supported.
The names of server options are the same as in .net, which have no "With.." prefixes. To keep the option names for server and client consistent, I would prefer names without without "With.."

**Comment by andig** [comment]
With #70 client reconnect, once implemented, should send errors to listeners if a reconnect fails but continue trying

**Comment by andig** [comment]
Is reconnection implemented?

**Comment by philippseith** [comment]
See #76
