### ISSUE TITLE
Use gofmt and goimports

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#71]
See https://www.jetbrains.com/help/go/integration-with-go-tools.html. Currently the code cannot be edited in e.g. Vscode without getting reformatted, at least for imports. These go tools should establish the standard formatting.

**Comment by philippseith** [comment]
I was already using go fmt. Goland has an option to do it on commit automatically. The key is using go imports instead go fmt.
To do so, I added a Filewatcher which does ` goimports -w $FilePath$` on save.

**Comment by philippseith** [comment]
See https://github.com/philippseith/signalr/pull/72
