### ISSUE TITLE
Re-add client.Stop()

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#80]
After https://github.com/philippseith/signalr/pull/76#issue-764918034, `Stop` has been removed without a replacement:

> To complete the API change, the Stop() method was removed, as stopping of the client could be done by canceling the context passed to NewClient()

and

> I finally got the intention here :-) and changed the meaning of the context.

I'd suggest to re-add `Stop`.

**Comment by philippseith** [comment]
PR welcome

**Comment by andig** [comment]
Just realized that this is still done using the context, so that's fine. Having stop is just a different approach then. As I understand, clients context controls the lifetime, the connections context the time to connect? Then that's matching ;)

**Comment by sruehl** [comment]
@philippseith I added a PR utilizing the context to stop https://github.com/philippseith/signalr/pull/166
