### ISSUE TITLE
go function leak in watchDog

### ISSUE THREAD

**Issue by jkristia** [philippseith/signalr#91]
Using 0.4.1
I think there is a go function leak in websocketconnection watchDog.

After running for 5 minutes with a few clients (browsers) connected I see a lot of pending go threads, and the list keep growing
![goleak](https://user-images.githubusercontent.com/3513311/140521675-2b20205f-2d3a-4f63-8620-029b6b2ca6c6.png)

**Comment by andig** [comment]
Probably caused by #90

**Comment by andig** [comment]
Should be fixed by #92

**Comment by philippseith** [comment]
Better take #96 in addition
